-- Seed data for Chukeles - A Coruña
INSERT INTO lugares (nombre, categoria, direccion, lat, lng, descripcion, telefono, sitioWeb, photo_url, aprobado) VALUES
('Parque de Santa Margarita', 'PARQUE', 'Rúa de Santa Margarita, s/n, 15005 A Coruña', 43.3619, -8.4111, 'Extenso parque ideal para pasear con perros, con amplias zonas verdes y mucha sombra.', '981 18 42 00', '', 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Parque_de_Santa_Margarita_A_Coru%C3%B1a.jpg', true),
('Clínica Veterinaria Elviña', 'VETERINARIO', 'Av. de Glasgow, 11, 15008 A Coruña', 43.3444, -8.4061, 'Servicio de urgencias y medicina general para mascotas.', '981 24 56 78', 'https://veterinariaelvina.com', 'https://www.publicdomainpictures.net/pictures/330000/velka/vet-office-veterinary-medicine.jpg', true),
('Playa de Riazor (Zona Canina)', 'PARQUE', 'Paseo Marítimo, 15004 A Coruña', 43.3689, -8.4109, 'Habilitada para perros durante la temporada permitida (consultar normativa municipal).', '', '', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Praia_de_Riazor_-_A_Coru%C3%B1a_-_Galicia_01.jpg/800px-Praia_de_Riazor_-_A_Coru%C3%B1a_-_Galicia_01.jpg', true),
('El Arca Centro Veterinario', 'VETERINARIO', 'Rúa Juan Flórez, 102, 15005 A Coruña', 43.3615, -8.4132, 'Especialistas en cirugía y diagnóstico avanzado.', '981 23 45 67', 'https://elarcaveterinaria.es', 'https://www.publicdomainpictures.net/pictures/330000/velka/vet-office-veterinary-medicine.jpg', true),
('Parque de Bens', 'PARQUE', 'Lugar de Bens, s/n, 15008 A Coruña', 43.3694, -8.4358, 'Antiguo vertedero convertido en un parque inmenso con vistas al mar y zona canina vallada.', '', '', 'https://www.galiciamaxica.eu/wp-contenido/uploads/2016/09/parque-bens-coruna-1-1024x680.jpg', true),
('Avenida Poodle', 'PELUQUERIA', 'Av. de Arteixo, 20, 15004 A Coruña', 43.3642, -8.4085, 'Peluquería canina de alta gama y tienda de accesorios.', '981 90 80 70', 'https://avenidapoodle.es', 'https://www.publicdomainpictures.net/pictures/470000/velka/pet-grooming-dog-bath.jpg', true),
('Dog Beach Riazor', 'OTRO', 'Praia de Riazor, 15004 A Coruña', 43.3698, -8.4124, 'Zona de arena permitida para perros en períodos específicos.', '', '', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Praia_de_Riazor_-_A_Coru%C3%B1a_-_Galicia_01.jpg/800px-Praia_de_Riazor_-_A_Coru%C3%B1a_-_Galicia_01.jpg', true),
('Parque de Eirís', 'PARQUE', 'Rúa Lamadosa, s/n, 15009 A Coruña', 43.3412, -8.3895, 'Parque moderno con zona de juegos y áreas para mascotas.', '', '', 'https://www.vigopeques.com/wp-contenido/uploads/2019/06/parque-eiris-coruna.jpg', true),
('Canis Pajaritas', 'VETERINARIO', 'Rúa das Pajaritas, 4, 15008 A Coruña', 43.3524, -8.4012, 'Atención personalizada y tienda especializada.', '981 12 13 14', '', 'https://www.publicdomainpictures.net/pictures/330000/velka/vet-office-veterinary-medicine.jpg', true),
('Montegatto Residencial', 'HOTEL', 'Oza-Cesuras, 15391 A Coruña', 43.2123, -8.2456, 'Residencia canina y centro de adiestramiento a las afueras de la ciudad.', '600 00 00 00', 'https://montegatto.com', 'https://www.hotelparaperros.net/images/bg_home.jpg', true);
